### PR TITLE
[BUGS-6802] add support for pecl as source to check

### LINKED ISSUE #13: Support for version checking latest package in PECL
Can use `curl` and `latest.txt` to get the latest version, e.g.:

```bash
oauth=$(curl -s https://pecl.php.net/rest/r/oauth/latest.txt) && echo $oauth
```

Output:
```bash
2.0.7
```

### PR DESCRIPTION
**Pull request by jazzsequence**
In https://github.com/pantheon-systems/cos-runtime-php (specifically [here](https://github.com/pantheon-systems/cos-runtime-php/blob/master/pantheon-php/build-php.sh#L146-L150)), we are actually using PECL as the source, but we're checking the GH mirror for versions. It's possible (see https://github.com/pantheon-systems/cos-runtime-php/pull/433  and https://github.com/php/pecl-web_services-oauth/tags as compared to https://pecl.php.net/package/oauth) that a package's version on GitHub might not match its version on PECL. This version mismatch can be confusing and problematic as we enact the Spiderman meme of figuring out which is the source of truth.

Spidermen pointing

This PR adds support for checking PECL for the latest version by making a `curl` request against the PECL API's `latest.txt` -- which is actually far simpler than checking the releases/tags on GitHub. Since we're sourcing from PECL, we should be able to check the actual source for the latest versions and use that rather than checking a source that's different from where we're actually getting the extension.

The actual change adds support for a new `source` param in the `dependencies.yml`. Currently, `github`, `pecl` and null (no value) are supported with `github` being the default if no `source` is defined. Tests and validations have been updated to support the new `dependencies.yml` parameter.

closes #13

### CODE REVIEW

File: bin/dependency-check-pr.sh [hunk 1]
```diff
@@ -2,6 +2,9 @@
 
 set -eou pipefail
 IFS=$'\n\t'
+white="\e[97m"
+green="\e[32m"
+reset="\e[0m"
```
Comment (pwtyler) [inline bin/dependency-check-pr.sh:7]: seeing these defined in multiple files. Would love to see a helper script that can be sourced with the values defined within functions— so something like

```
#!/bin/bash
# no flags here

white="\e[97m"
green="\e[32m"
reset="\e[0m"

echo_green(){
  echo -e "Current Tag: ${green}${1:-}${reset}"
}
```
then in this script you `source $INC/echo-colors.sh` and then `echo_green "foo"`

Comment (jazzsequence) [reply bin/dependency-check-pr.sh:7]: hmm...not sure I'm kosher with the idea of helper functions. Because it's used in different contexts, actual usage would need to be something like `echo -e "Current Tag: $(echo_green $(1:-))"` because that's not the only text that we would output -- and at that point there's not much difference between that and the current syntax. However sourcing the color variables might be worth doing. Not sure it's worth it for this PR though, since it's just cosmetic.

Comment (greg-1-anderson) [reply bin/dependency-check-pr.sh:7]: Write Everything Twice

Comment (pwtyler) [reply bin/dependency-check-pr.sh:7]: ah you're right I wasn't capturing the fact that part of the string is not green. agree sourcing the colors separately can be done elsewhere.

File: bin/dependency-check-pr.sh [hunk 2]
```diff
@@ -22,22 +25,21 @@ main() {
 
     local CURRENT_TAG
     CURRENT_TAG="$(yq ".dependencies.${NAME}.current_tag" "${DEPENDENCIES_YML}")"
-    echo "Current Tag: ${CURRENT_TAG}"
+    echo -e "Current Tag: ${white}${CURRENT_TAG}${white}"
```
Comment (pwtyler) [inline bin/dependency-check-pr.sh]:
```suggestion
    echo -e "Current Tag: ${white}${CURRENT_TAG}${reset}"
```
should this be reset at the end?

File: bin/dependency-check-pr.sh [hunk 3]
```diff
@@ -124,7 +126,33 @@ ${PR_NOTE}"
...
+
+# Get the latest tag from the source. If source is undefined, default to "github".
+# Usage example: LATEST_TAG=$(get_latest_tag "mongodb-php-library" "pecl")
+get_latest_tag() {
+  local repo="$1"
+  local source="$2"
+  local LATEST_TAG
+
+  # We're defaulting to GitHub, but we want to check against releases AND tags.
+  if [[ "${source}" == "github" || "${source}" == "null" ]]; then
```
Comment (pwtyler) [inline bin/dependency-check-pr.sh]: "null" is a weird yq-ism, I'd make this `|| ""` within the function as well for cleaner coverage.
```suggestion
  if [[ "${source}" == "github" || "${source}" == "null" || "${source}" == "" ]]; then
```

File: bin/test-textfile.sh [hunk 4]
```diff
@@ -43,11 +44,11 @@ while IFS= read -r line; do
 
     # Output the extension name being checked
     echo "Validating version for $formatted_name..."
-	echo "Found $version!"
+	echo -e "${white}Found $version!${reset} ✅"
 
     # Check if the version matches the pattern
     if [[ ! $version =~ $version_pattern ]]; then
-        echo "Invalid version: $version"
+        echo -e "${white}Invalid version: $version${red} ❌"
```
Comment (pwtyler) [inline bin/test-textfile.sh]: should this be red -> reset?

Comment (jazzsequence) [reply bin/test-textfile.sh]: no, it should just reset. I was trying to make the versions more visible. Although maybe making the whole thing red makes sense, too.

Comment (jazzsequence) [reply bin/test-textfile.sh]:
```suggestion
        echo -e "${red}Invalid version: $version${reset} ❌"
```

**Review by pwtyler — APPROVED** [review]
